# Generated by Django 3.2.7 on 2021-10-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='doctor',
        ),
        migrations.AddField(
            model_name='reservation',
            name='doctor',
            field=models.ManyToManyField(to='hospitals.Doctor'),
        ),
    ]
