# Generated by Django 3.2.7 on 2021-10-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_auto_20211020_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='doctor',
            field=models.ManyToManyField(related_name='patients', to='hospitals.Doctor'),
        ),
    ]
