# Generated by Django 3.2.7 on 2021-10-20 00:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_alter_reservation_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='symptom',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ManyToManyField(through='hospitals.Reservation', to='hospitals.Doctor'),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='doctor',
        ),
        migrations.AddField(
            model_name='reservation',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hospitals.doctor'),
            preserve_default=False,
        ),
    ]
